### ISSUE TITLE
Should this use okhttp-api-plugin?

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkinsci/azure-ad-plugin#172]
Azure AD plugin version 185.v3b416408dcb1 includes com.squareup.okhttp3:okhttp:4.9.1 in the HPI package. Would it be a good idea to depend on the [OkHttp](https://plugins.jenkins.io/okhttp-api/) API plugin instead?

**Comment by timja** [comment]
not sure, bit scared to force a downgrade that far.

cc @bitwiseman @car-roll @dwnusbaum as maintainers of the API plugin

**Comment by KalleOlaviNiemitalo** [comment]
Oh, I didn't realize the API plugin carried an older version.

**Comment by dwnusbaum** [comment]
IDK whether the OkHttp dependency is being used directly by this plugin or is a transitive dependency of some Azure libraries. I am also not sure about any the changes from OkHttp 3 3.x to 4.x (if there are incompatible changes but OkHttp changed package names, then we could introduce a new API plugin).

If you are using OkHttp directly in your plugin, then yes definitely I would recommend switching the API plugin.

If some Azure libraries are using OkHttp on their own internally, you are kind of in an awkward situation. If you ever add a dependency on a plugin that itself depends on `okhttp-api` (or if a plugin you already depend on adds an `okhttp-api` dependency in an update), then your plugin's locally bundled version of `okhttp` will be ignored in favor of the version from the API plugin due to [the way Jenkins plugin classloading works](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/). If you are worried about this, then you could go ahead and test whether the Azure libraries are able to use the older version of OkHttp without issue. If everything works, then you could switch to the API plugin, but you would need to do real-world testing (or maybe a `RealJenkinsRule` test would suffice?) every time the Azure libraries are updated to make sure they don't start using a feature that the old version of OkHttp does not have.

If it turns out that you really need the latest version of OkHttp, _and_ you need to pick up a dependency on a plugin that uses the API plugin, things get really awkward. See [here](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#pluginfirstclassloader-and-its-discontents) for some options but these are kind of a last resort.

Also, if the changes from OkHttp 3 3.x to 4.x are largely backwards-compatible, you could propose an update to the API plugin so that plugin developers can use it without having to worry about these kinds of issues.

**Comment by timja** [comment]
There looks to be some abandoned work in the README here:
https://github.com/jenkinsci/okhttp-api-plugin#updating-to-a-newer-version-of-okhttp

Basically I'm happy to use the API plugin.

But right now it works and I don't really want to use a plugin that's pinned to such an old version.

and I don't want to pick up the work currently to update the API plugin, (maybe in the future).

> If you are using OkHttp directly in your plugin, then yes definitely I would recommend switching the API plugin.

Yes this plugin uses it in one place

> If some Azure libraries are using OkHttp on their own internally, you are kind of in an awkward situation

Yes they are, more difficulty though the libs come from https://github.com/jenkinsci/azure-sdk-plugin which doesn't use those, most of the Azure APIs default to using a netty http client, but the Azure graph APIs are default to okhttp and there was some problem when I tried to use netty, I think in a quick look I couldn't figure out how to make the type signatures work.

**Comment by dwnusbaum** [comment]
> Yes this plugin uses it in one place

Sorry, just to clarify, my comment should have been "if you are _only_ using OkHttp directly ...". Since you have a library that uses `okhttp` as well, keeping that library working is the main consideration in my opinion.

> But right now it works and I don't really want to use a plugin that's pinned to such an old version.
>
> and I don't want to pick up the work currently to update the API plugin, (maybe in the future).

Yeah that's definitely fair. Just be careful when adding or updating plugin dependencies to make sure `okhttp-api` does not get pulled in by surprise.

**Comment by bitwiseman** [comment]
> There looks to be some abandoned work in the README here: https://github.com/jenkinsci/okhttp-api-plugin#updating-to-a-newer-version-of-okhttp
> 
> Basically I'm happy to use the API plugin.
> 
> But right now it works and I don't really want to use a plugin that's pinned to such an old version.

This is totally fair.  From what I know, the move from 3.x to 4.x is indeed largely backward compatible, but I chose not to move to the later versions to avoid any possibility of breakage.  

When the `okhttp-api-plugin` was created my analysis showed that this plugin used `okttp-urlconnection` which is not supported in 3.14.x and later.  It looks like that dependency has since been removed, which unblocks this plugin from using `okhttp-api-plugin` .  

Looking at the release notes for okhttp, I think it is reasonable to update to 4.8.1.  I will put in a PR for that now. 

> and I don't want to pick up the work currently to update the API plugin, (maybe in the future).
> 
> > If you are using OkHttp directly in your plugin, then yes definitely I would recommend switching the API plugin.
> 
> Yes this plugin uses it in one place
> 
> > If some Azure libraries are using OkHttp on their own internally, you are kind of in an awkward situation
> 
> Yes they are, more difficulty though the libs come from https://github.com/jenkinsci/azure-sdk-plugin which doesn't use those, most of the Azure APIs default to using a netty http client, but the Azure graph APIs are default to okhttp and there was some problem when I tried to use netty, I think in a quick look I couldn't figure out how to make the type signatures work.

**Comment by bitwiseman** [comment]
https://github.com/jenkinsci/okhttp-api-plugin/pull/55

**Comment by timja** [comment]
All the maintained azure plugins have had their dependencies modernised, there’s a few abandoned ones but they are all likely broken anyway

**Comment by timja** [comment]
Done in https://github.com/jenkinsci/azure-ad-plugin/pull/209
