### ISSUE TITLE
Matrix-based security not working with Groups

### ISSUE THREAD

**Issue by petvaa01** [jenkinsci/azure-ad-plugin#68]
I have configured AAD and azure-ad-plugin according to the instructions with option 2 and I'm able to login to Jenkins.

Looking my jenkins user the groups are being populated from AAD to it:
![Screenshot 2020-01-08 at 16 57 04](https://user-images.githubusercontent.com/32452536/71988782-2e53f400-3239-11ea-87f9-bf4efa231324.png)

I am now trying to setup Matrix-based security with the groups by adding a group my user belongs to and giving it all access
![Screenshot 2020-01-08 at 16 55 50](https://user-images.githubusercontent.com/32452536/71988784-2e53f400-3239-11ea-9d5d-fc96fbb72f52.png)

All seems to work fine, but I'm unable to build jobs as I'm lacking permissions to run agent
![Screenshot 2020-01-08 at 16 56 24](https://user-images.githubusercontent.com/32452536/71988780-2e53f400-3239-11ea-98a6-d36b0200dc7b.png)

If I give my user directly Agent/Build permissions the build starts to run
![Screenshot 2020-01-08 at 17 29 35](https://user-images.githubusercontent.com/32452536/71990825-c2738a80-323c-11ea-8b97-a55d546e031e.png)

I'm not seeing any errors in the logs.

**Comment by gavinfish** [comment]
I think this issue may be caused by the order of the authentication? I have below settings and everything works fine.
![Annotation 2020-01-09 133837](https://user-images.githubusercontent.com/6169722/72041128-a972e400-32e5-11ea-9659-66d6398b591a.png)

**Comment by eranreshef** [comment]
Even though the order is not controllable, I've made some manipulations to test this suggestion and it still fails with the same problem.

**Comment by hikkyXII** [comment]
@petvaa01, If issue still persists, please check latest plugin version.

**Comment by timja** [comment]
most likely fixed in the latest version, 

Otherwise needs more steps to reproduce.

From scratch how can someone set this up.

How is the agent configured to restrict permissions etc.

(I'm somewhat aware you can do that but not exactly how, it's possible this plugin doesn't support it properly but the issue description isn't enough for someone unfamiliar with the specific are to reproduce).

I'm going to close this, but feel free to open with more steps to reproduce
