### ISSUE TITLE
Groups aren't populated

### ISSUE THREAD

**Issue by mrdfuse** [jenkinsci/azure-ad-plugin#7]
I tested this piece of code in the Jenkins script console:

```
import com.microsoft.jenkins.azuread.*

def uid = '9c3c7a4e-0bee-42c9-9598-4cbbe6a557e4'

def jenkins = Jenkins.getInstance()
def realm = jenkins.getSecurityRealm()

def groups = AzureCachePool.get(realm.getAzureClient()).getBelongingGroupsByOid(uid)
println(groups)
// works as expected, I see all the objectids of the groups

def auths = User.current().getAuthorities()
println(auths)
// auths is empty, shouldn't it be the same as 'groups'?
```

Retrieving the groups seems to work fine, however my user doesn't have any.  The code seems simple though: https://github.com/jenkinsci/azure-ad-plugin/blob/dev/src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java#L244

Any ideas?

**Comment by mrdfuse** [comment]
After some digging in the source code of the plugin and Jenkins using this script:
```
import com.microsoft.jenkins.azuread.*
import jenkins.security.*
import org.acegisecurity.context.SecurityContextHolder
import org.acegisecurity.Authentication

def uid = '9c3c7a4e-0bee-42c9-9598-4cbbe6a557e4'

def jenkins = Jenkins.getInstance()
def realm = jenkins.getSecurityRealm()

def user = User.getById(uid, false)
// just to verify I have the right user
println(user.getFullName())
println()

def groups = AzureCachePool.get(realm.getAzureClient()).getBelongingGroupsByOid(uid)
println("azure retrieved groups: " + groups)
// works as expected, I see all the objectids of the groups

def auths = user.getAuthorities()
println("jenkins user authorities: " + auths)
// auths is empty, shouldn't it be the same as 'groups'?


def auth = SecurityContextHolder.getContext().getAuthentication()
print("security context authorities: ")
auth.getAzureAdUser().getAuthorities().eachWithIndex { g, i ->
  if (i < auth.getAzureAdUser().getAuthorities().size() -1) {
	print(g.getAuthority() + " ")
	// println(g.getGroupName())
  }
}
println()

println("user has admin permissions: " + Jenkins.getInstance().hasPermission(Jenkins.ADMINISTER))

// Jenkins calls this code for user.getAuthorities()
def authImpers = user.impersonate()

println("# of authorities in authentication object: " + authImpers.getAuthorities().size())

userDetailsService = new ImpersonatingUserDetailsService(realm.getSecurityComponents().userDetails)
userDetails = userDetailsService.loadUserByUsername(uid)

println(authImpers.getDetails())
println(authImpers.getPrincipal())
```

I arrived at https://github.com/jenkinsci/azure-ad-plugin/blob/dev/src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java#L273

Because the SecurityRealm throws:
```
hudson.security.UserMayOrMayNotExistException: Cannot verify users in this context
	at com.microsoft.jenkins.azuread.AzureSecurityRealm$4.loadUserByUsername(AzureSecurityRealm.java:273)
```
the 'User' object will never be populated with authorities (exception is swallowed by Jenkins in https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/User.java#L352 and a minimal user is returned. 
Is this the intent of this plugins code? Will it work then to use groups in matrix or role based auth strategies?

**Comment by sgautrin** [comment]
I'm late to the party, but did you grant the “Read all groups” permission to your registered app in Azure AD?

**Comment by mrdfuse** [comment]
Yes:
![image](https://user-images.githubusercontent.com/532066/43573365-ddb58cdc-9641-11e8-9f35-47e569c68f3c.png)

As I reread my previous comments, it seems the code is bugged but I'm not 100% sure. I was hoping someone else could tell it works for him, or the author of the code could confirm that the exception was thrown on purpose and has no impact on loading the groups.

**Comment by sgautrin** [comment]
In your capture the “Read all groups” permission (in “Delegated Permissions”) is not selected. Only “Read directory data” and “Sign in and read user profile” are.

The UI is not the clearest though, with the attention attracted by the coloured checks on the right, while they only indicate if you need an admin to grant the permission after your request them for the app.

**Comment by mrdfuse** [comment]
Aaah stupid, you are right about the rights. But I have corrected it now and the code still gives the same exceptions, and the it still doesn't work in Jenkins.

**Comment by sgautrin** [comment]
I did not encounter that specific issue; however from the look of it it would seem the app permissions are not actually all effective: after selecting the permissions in the screen above, did you also “grant permissions” with an admin account? The “UserMayOrMayNotExistException” seems to indicate that it can not know if the user exists or not, and thus lack permissions to do so.

![azure-ad-grant-permissions](https://user-images.githubusercontent.com/2393167/43586922-33c3a696-9669-11e8-9354-34f13095ce80.png)

“Read directory data” and “Sign in and read user profile” require an admin to effectively grant the permissions after they've been selected for the app.

**Comment by mrdfuse** [comment]
Ha, I can't tell how many times we have forgot to 'Grant permissions' at work. So many times that it's ingrained into our memory for life. So no :)

The thing is, that exception is thrown unconditionally: https://github.com/jenkinsci/azure-ad-plugin/blob/dev/src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java#L273
No checks are being made, so it doesn't matter what I do in Azure, as soon as Jenkins calls that code the exception is thrown.

**Comment by sgautrin** [comment]
You got me curious and I looked a bit around, and most other plugins either:
- do not define the UserDetailsService, and thus use a https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/security/UserDetailsServiceProxy.java apparently with no delegate initialised, with [openid-plugin](https://github.com/jenkinsci/openid-plugin/blob/bc0db50d1e67af115230f1e5c960a064e72effa7/src/main/java/hudson/plugins/openid/OpenIdSsoSecurityRealm.java) indicating in a comment that it is not specified because OpenId does not provide a way to query about other users
- define a UserDetailsService doing the same as this plugin, throwing an exception for `loadUserByUsername`

I found mainly the saml-plugin providing an actual implementation of UserDetailsService.

The `User#getAuthorities()` method does not seem to be meant to access group information of the current user, and will “impersonate” the user even for the current user, with this getting only minimal information when the backend does not support querying other users information, indicated among other things by the fact that `userDetailsService.loadUserByUsername(id);` throws a `UserMayOrMayNotExistException` (the comment in the exception handling being relatively explicit as well, `// backend can't load information about other users. so use the stored information if available`).

Now if your initial test script was only to debug why your user had no group when logging through Azure, then you should test again simply authenticating and granting permissions based on Azure group within Jenkins, as in my case although your test code produces the same result as in your case, I can grant users permissions based on Azure groups with Role-Based Strategy. To be noted though that I had to reference the groups by their GUID and not their name (i'll need to investigate what's mentioned in  [this issue](https://github.com/jenkinsci/azure-ad-plugin/issues/11) a bit).

**Comment by mrdfuse** [comment]
Wauw thanks for all the effort!
I got it working now, after I fixed the missing permission I tested it by adding a group, without adding any permission and saving. After reloading the roles page the group was gone again, I presumed because it couldn't find it, but I guess it was because I didn't check any permission.
I did it again now but checked a permission and it works, with guid.

So the missing permission was the cause after all...
