### ISSUE TITLE
Is there no way to use this plugin to authorize using a role-based matrix authorization strategy?

### ISSUE THREAD

**Issue by heckerdj** [jenkinsci/azure-ad-plugin#80]
Seems like all of the instructions require use of 'Azure Active Directory Matrix-based security', why is it that there is no option to use a Azure Active Directory Role-Based Matrix security?

**Comment by timja** [comment]
Yes this is supported, docs are coming in https://github.com/jenkinsci/azure-ad-plugin/pull/118

You can view them at https://github.com/timja/azure-ad-plugin/blob/msal/README.md

**Comment by c-mckenzie** [comment]
> Yes this is supported, docs are coming in #118
> 
> You can view them at https://github.com/timja/azure-ad-plugin/blob/msal/README.md

Hi timja, 

The doc you linked mentioned the role-strategy plugin as supported but this isn't the same thing as using Azure AD App Roles, is there actually a way to use to substitute roles in place of security groups as the groups claim?

App Roles in Azure AD are handy because you don't require a tenant admin to approve any additional permissions and it can be a good alternative if you have issues with users that are members of a large numbers of groups ( e.g. #75 )

**Comment by timja** [comment]
You don’t need a tenant admin to approve groups either? As long you modify the manifest to send the groups they will be included in the id_token when authenticating 

no this doesn’t support app registration roles

**Comment by heckerdj** [comment]
As @c-mckenzie mentioned the issue that I am facing is due to large numbers of groups on a single user. It is not feasible to manage every possible group in the manifest, or to dynamically add new roles every time a new team/group comes along. This creates lots of extra legwork to achieve the same desired result that already exists when just using the standard role-based matrix connected to an Active Directory. 

I currently have Azure AD acting as a collection of multiple pre existing AD forests and would like to be able to connect to it as I would one single AD instance preventing the delays caused by connecting every individual forest directly.

**Comment by timja** [comment]
https://github.com/jenkinsci/azure-ad-plugin/pull/118 Should support unlimited groups, does that help?
